# Generated by Django 4.2 on 2024-10-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
