# Generated by Django 4.2 on 2024-10-11 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_delete_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Senal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='senales/', verbose_name='Imagen de Ejemplo')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video de Ejemplo')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leccion')),
            ],
            options={
                'verbose_name': 'Señal',
                'verbose_name_plural': 'Señales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('intentos', models.IntegerField(default=0, verbose_name='Número de Intentos')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leccion')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
                'ordering': ['usuario', 'nivel', 'leccion'],
            },
        ),
        migrations.AddField(
            model_name='leccion',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nivel'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento_correcto', models.BooleanField(default=False, verbose_name='Intento Correcto')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Intento')),
                ('intentos_incorrectos', models.IntegerField(default=0, verbose_name='Intentos Incorrectos')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje de Feedback')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leccion')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nivel')),
                ('progreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.progreso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
