# Generated by Django 4.2 on 2024-10-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['orden'], 'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AddField(
            model_name='nivel',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
