# Generated by Django 4.2 on 2024-10-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nivel_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='desbloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
