# Generated by Django 4.2 on 2024-10-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_feedback_fecha_intento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Es el nivel final'),
        ),
    ]
